Downloads/Tugas Akhir Nurma/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PakarController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\helper\Rumus;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     echo "Hello World"; 
// });

Route::get('/login',[LoginController::class,'index'])->name('login')->middleware('guest');
Route::get('/loginadmin',[PakarController::class,'pakarlogin'])->name('pakarlogin');
Route::post('/login-proses',[LoginController::class,'login_proses'])->name('login-proses');
Route::post('/loginadmin-proses',[PakarController::class,'pakarlogin_proses'])->name('pakarlogin-proses');
Route::get('/logout',[LoginController::class,'logout'])->name('logout');
Route::get('/register',[LoginController::class,'register'])->name('register');
Route::post('/register-proses',[LoginController::class,'register_proses'])->name('register-proses');

Route::group(['prefix' => 'admin', 'as' => 'admin.'] , function(){
Route::get('/dashboard',[HomeController::class,'dashboard'])->name('dashboard');

Route::get('/user',[HomeController::class,'index'])->name('index');

Route::get('/edituser/{id}',[HomeController::class,'edituser'])->name('edituser');
Route::put('/updateuser/{id}',[HomeController::class,'updateuser'])->name('updateuser');
Route::delete('/deleteuser/{id}',[HomeController::class,'deleteuser'])->name('deleteuser');

Route::get('/pakar',[PakarController::class,'indexpakar'])->name('indexpakar');
Route::get('/createpakar',[PakarController::class,'createpakar'])->name('createpakar');
Route::post('/storepakar',[PakarController::class,'storepakar'])->name('storepakar');

Route::get('/editpakar/{id}',[PakarController::class,'editpakar'])->name('editpakar');
Route::put('/updatepakar/{id}',[PakarController::class,'updatepakar'])->name('updatepakar');
Route::delete('/deletepakar/{id}',[PakarController::class,'deletepakar'])->name('deletepakar');

Route::get('/kesiapanpsikologis',[HomeController::class,'kesiapanpsikologis'])->name('kesiapanpsikologis');
Route::get('/createkesiapanpsikologis',[HomeController::class,'createkesiapanpsikologis'])->name('createkesiapanpsikologis');
Route::post('/storekesiapanpsikologis',[HomeController::class,'storekesiapanpsikologis'])->name('storekesiapanpsikologis');

Route::get('/editkesiapanpsikologis/{id}',[HomeController::class,'editkesiapanpsikologis'])->name('editkesiapanpsikologis');
Route::put('/updatekesiapanpsikologis/{id}',[HomeController::class,'updatekesiapanpsikologis'])->name('updatekesiapanpsikologis');
Route::delete('/deletekesiapanpsikologis/{id}',[HomeController::class,'deletekesiapanpsikologis'])->name('deletekesiapanpsikologis');


Route::get('/jawabanuser',[HomeController::class,'jawabanuser'])->name('jawabanuser');

Route::get('/print-data/{id}',[HomeController::class,'getDataPrint']);

});

Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
Route::get('/dashboarduser',[HomeController::class,'dashboarduser'])->name('dashboarduser');

Route::get('/analisis',[HomeController::class,'indexanalisis'])->name('indexanalisis');
Route::post('/storeanalisis',[HomeController::class,'storeanalisis'])->name('storeanalisis');
Route::delete('/deleteanalisis/{id}',[HomeController::class,'deleteanalisis'])->name('deleteanalisis');
Route::get('/analisispsikologis1',[HomeController::class,'analisispsikologis1'])->name('analisispsikologis1');
Route::post('/storepsikologis',[HomeController::class,'storepsikologis'])->name('storepsikologis');
Route::get('/analisispsikologis2',[HomeController::class,'analisispsikologis2'])->name('analisispsikologis2');
Route::get('/hasilanalisis/{id}',[HomeController::class,'hasilanalisis'])->name('hasilanalisis');
Route::get('/psikologispernikahan',[HomeController::class,'infopsikologis'])->name('infopsikologis');
Route::get('/infopranikah',[HomeController::class,'infopranikah'])->name('infopranikah');

});

Route::get('/rumus-user-helper-demo', function () {
    return Rumus::CFCombine(2, 5);
});

Downloads/Tugas Akhir Nurma/resources/views/dashboard.blade.php
@extends('layout.main')
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <!-- <h1 class="m-0">Dashboard</h1> -->
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <style>
      .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */
    color: white; /* Warna teks yang kontras dengan latar belakang */
}
</style>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
        <div class="col-lg-3 col-6">
            <!-- small box -->
          <div class="small-box bg-secondary">
              <div class="inner">
              <h3>
              {{ $pakar = App\Models\pakar::get()->count() }}
</h3>
                <p>Total Pakar</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="{{ route('admin.indexpakar') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
              <h3>
    {{ $data = App\Models\User::get()->count() }}
</h3>
                <p>Total User</p>
              </div>
              <div class="icon">
              <i class="ion ion-person"></i>
              </div>
              <a href="{{ route('admin.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
                <h3>{{ $pertanyaan = App\Models\kesiapanpsikologis::get()->count() }}<sup style="font-size: 20px"></sup></h3>
                <p>Total Pertanyaan</p>
              </div>
              <div class="icon">
              <i class="fas fa-list"></i>
              </div>
              <a href="{{ route('admin.kesiapanpsikologis') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
              <h3>
    {{ $analisis = App\Models\jawaban::get()->count() }}
</h3>

                <p>Total Konsultasi</p>
              </div>
              <div class="icon">
              <i class="fas fa-history"></i> <!-- Ini adalah contoh ikon riwayat -->
              </div>
              <a href="{{ route('admin.jawabanuser') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
       
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
@endsection

Downloads/Tugas Akhir Nurma/resources/views/edituser.blade.php
@extends('layout.main')

@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-4">
        <div class="col-sm-12 text-center">
            <h3 class="title">FORM EDIT USER</h3>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Edit User</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <style>
    .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }
        .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */  
      }
      .container-fluid {
        max-width: 800px; /* Set the maximum width of the container */
        margin: 0 auto; /* Center the container */
        padding: 20px; /* Add some padding */
      }
      .card{
      background-color: #eff5ec;
      font-family: 'Times New Roman', Times, serif; 
    }
    </STYLE>
    <section class="content">
      <div class="container-fluid">
            <form action="{{ route('admin.updateuser',['id' => $data->id]) }}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
          <!-- left column -->
          <div class="col-md-6 offset-md-3"> <!-- Add offset-md-3 to center the column -->
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <!-- <h3 class="card-title">Form Edit Data Pakar</h3> -->
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form>
                <div class="card-body">
                <div class="form-group">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ $data->email }}" placeholder="Enter email"> 
                    @if ($errors->has('email'))
                        <small class="form-text text-danger">{{ $errors->first('email') }}</small>
                    @endif
                </div>
                  <div class="form-group">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                    @if ($errors->has('password'))
                        <small class="form-text text-danger">{{ $errors->first('password') }}</small>
                    @endif
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
  <button type="submit" class="btn btn-primary float-right">SUBMIT</button>
                </div>
                </div>
                </div>
                </div>
              </form>
        </form>
      </div><!-- /.container-fluid -->
    </section>
  </div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                                  
@endif
@endsection

Downloads/Tugas Akhir Nurma/resources/views/index.blade.php
@extends('layout.main')
@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />
@endsection
@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-12">
            <h3 class="title">DATA USER</h3>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Data User</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <style>
  table {
    width: 100%; /* Sesuaikan lebar tabel sesuai kebutuhan */
    text-align: left;
    }
    .faktor-column {
      white-space: pre-line;
      word-wrap: break-word;
      max-width: 140px; 
    }
    .card{
    background-color: #eff5ec;
    font-family: 'Times New Roman', Times, serif; 
    margin-right: 30px; /* Adds left and right margins */
    margin-left:30px; 
    text-align: center;
    }
    .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */
    }
    .top-right-button {
      background-color: #343a40; /* Abu-abu tua */
            border-color: #343a40; /* Abu-abu tua */
            color: white;
            margin-top: 5px; /* Adjust this value as needed */
        }
        .btn-dark-gray {
            background-color: #343a40; /* Abu-abu tua */
            border-color: #343a40; /* Abu-abu tua */
            color: white;
            font-family: 'Times New Roman', Times, serif;
        }
        .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }
        /* padding-left: 100px;
        padding-right: 80px; */
        #serverside th,
#serverside td {
    text-align: center;
    vertical-align: middle; /* Ensures text is vertically centered as well */
    background-color: #eff5ec;
}

/* Optional: Add some styling to the table */
#serverside {
    width: 100%; /* Adjust this value to set the table width as needed */
    border-collapse: collapse; /* Ensures there is no space between table cells */
    text-align: center;
}

#serverside th,
#serverside td {
    padding: 10px; /* Adds some padding for better readability */
    border: 1px solid #ddd; /* Adds a border to the cells */
    text-align: center;
}

#serverside th {
    background-color: #eff5ec; /* Adds a background color to the header */
}
      
  </style>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <div class="row">
          <div class="col-12">
          
            <div class="card">
              <div class="card-header">

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <!-- <input type="text" name="table_search" class="form-control float-right" placeholder="Search"> -->

                    <div class="input-group-append">
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap" id="user">
                  <thead>
                    <tr>
                      <th>No.</th>
                      <th>Email</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($data as $d)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td class="faktor-column">{{ $d->email }}</td>
                            <td>
                                <a href="{{ route('admin.edituser',['id' => $d->id]) }}" class="btn btn-primary"><i class="fas fa-pen"></i>Edit</a>
                                <a data-toggle="modal" data-target="#modal-hapus{{ $d->id }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i>Hapus</a>
                            </td>
                        </tr>
                        <div class="modal fade" id="modal-hapus{{ $d->id }}">
                        <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning">
        <h4 class="title">Konfirmasi Hapus Data</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
                <div class="modal-body">
        <p class="text-center">Apakah kamu yakin ingin menghapus data pengguna <b>{{ $d->email }}</b>?</p>
      </div>
      <form action="{{ route('admin.deleteuser',['id' => $d->id]) }}" method="POST">
        @csrf
        @method('DELETE')
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
          <button type="submit" class="btn btn-danger">Ya, Hapus</button>
        </div>

                </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
                    @endforeach    
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                                  
@endif
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
<script>
$(document).ready( function () {
    $('#user').DataTable();
} );
</script>
@endsection

Downloads/Tugas Akhir Nurma/resources/views/pakarlogin.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Login Admin</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
  <link rel="stylesheet" href="style.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Great+Vibes&display=swap">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="logo">
            <img src="{{ asset('/lte/dist/img/logo2.png') }}" alt="Logo" class="logo-img">
        </div>
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="{{ route('pakarlogin') }}" class="h2"><b>WELCOME</b>admin!</a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Halo, masuk untuk menjadi admin</p>

      <form action="{{ route('pakarlogin-proses') }}" method="post">
        @csrf
        @error('email')
            <small class="form-text text-danger">{{ $errors->first('email') }}</small>
          @enderror
        <div class="input-group mb-3">
          <input type="email" name="email" class="form-control" placeholder="Masukkan Email" value="{{ old('email') }}">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        
        @error('password')
            <small class="form-text text-danger">{{ $errors->first('password') }}</small>
          @enderror
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Masukkan Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Masuk</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{{ asset('lte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('lte/dist/js/adminlte.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>


<style>
.card-outline.card-primary {
  padding: 6px 10px;
    margin-bottom: 0;
    border: none;
    background-color: rgba(0,0,0,.4);
    box-shadow: 0 0 30px rgba(255,255,255,.3);
    border-bottom: 2px solid #2979ff;
    color: #fff;
    margin-top: 50px;
}
.text-center {
  color: white;
}

.form-control{
  background-color: transparent;
}
*{
    margin-bottom: 0;
    padding: 0;
    outline: 0;
    font-family: 'Open Sans', sans-serif;
}
body{
    height: 100vh;
    background-image: url("{{ asset('/lte/dist/img/LOGINBARU2.jpeg') }}" );
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
}
.logo {
            position: absolute;
            top: 0;
            left: 0;
            padding: 20px;
        }
        
        .logo-img {
            max-width: 350px; /* Sesuaikan lebar logo */
            height: auto;
        }
</style>

@if($message = Session::get('failed'))
<script>
Swal.fire({
  icon: "error",
  title: "Oops...",
  text: "{{ $message }}",
});         
</script>                                  
@endif

@if($message = Session::get('success'))
<script>
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 1500
});
</script>                                  
@endif

</body>
</html>