Downloads/Tugas Akhir Nurma/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PakarController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\helper\Rumus;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     echo "Hello World"; 
// });

Route::get('/login',[LoginController::class,'index'])->name('login')->middleware('guest');
Route::get('/loginadmin',[PakarController::class,'pakarlogin'])->name('pakarlogin');
Route::post('/login-proses',[LoginController::class,'login_proses'])->name('login-proses');
Route::post('/loginadmin-proses',[PakarController::class,'pakarlogin_proses'])->name('pakarlogin-proses');
Route::get('/logout',[LoginController::class,'logout'])->name('logout');
Route::get('/register',[LoginController::class,'register'])->name('register');
Route::post('/register-proses',[LoginController::class,'register_proses'])->name('register-proses');

Route::group(['prefix' => 'admin', 'as' => 'admin.'] , function(){
Route::get('/dashboard',[HomeController::class,'dashboard'])->name('dashboard');

Route::get('/user',[HomeController::class,'index'])->name('index');

Route::get('/edituser/{id}',[HomeController::class,'edituser'])->name('edituser');
Route::put('/updateuser/{id}',[HomeController::class,'updateuser'])->name('updateuser');
Route::delete('/deleteuser/{id}',[HomeController::class,'deleteuser'])->name('deleteuser');

Route::get('/pakar',[PakarController::class,'indexpakar'])->name('indexpakar');
Route::get('/createpakar',[PakarController::class,'createpakar'])->name('createpakar');
Route::post('/storepakar',[PakarController::class,'storepakar'])->name('storepakar');

Route::get('/editpakar/{id}',[PakarController::class,'editpakar'])->name('editpakar');
Route::put('/updatepakar/{id}',[PakarController::class,'updatepakar'])->name('updatepakar');
Route::delete('/deletepakar/{id}',[PakarController::class,'deletepakar'])->name('deletepakar');

Route::get('/kesiapanpsikologis',[HomeController::class,'kesiapanpsikologis'])->name('kesiapanpsikologis');
Route::get('/createkesiapanpsikologis',[HomeController::class,'createkesiapanpsikologis'])->name('createkesiapanpsikologis');
Route::post('/storekesiapanpsikologis',[HomeController::class,'storekesiapanpsikologis'])->name('storekesiapanpsikologis');

Route::get('/editkesiapanpsikologis/{id}',[HomeController::class,'editkesiapanpsikologis'])->name('editkesiapanpsikologis');
Route::put('/updatekesiapanpsikologis/{id}',[HomeController::class,'updatekesiapanpsikologis'])->name('updatekesiapanpsikologis');
Route::delete('/deletekesiapanpsikologis/{id}',[HomeController::class,'deletekesiapanpsikologis'])->name('deletekesiapanpsikologis');


Route::get('/jawabanuser',[HomeController::class,'jawabanuser'])->name('jawabanuser');

Route::get('/print-data/{id}',[HomeController::class,'getDataPrint']);

});

Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
Route::get('/dashboarduser',[HomeController::class,'dashboarduser'])->name('dashboarduser');

Route::get('/analisis',[HomeController::class,'indexanalisis'])->name('indexanalisis');
Route::post('/storeanalisis',[HomeController::class,'storeanalisis'])->name('storeanalisis');
Route::delete('/deleteanalisis/{id}',[HomeController::class,'deleteanalisis'])->name('deleteanalisis');
Route::get('/analisispsikologis1',[HomeController::class,'analisispsikologis1'])->name('analisispsikologis1');
Route::post('/storepsikologis',[HomeController::class,'storepsikologis'])->name('storepsikologis');
Route::get('/analisispsikologis2',[HomeController::class,'analisispsikologis2'])->name('analisispsikologis2');
Route::get('/hasilanalisis/{id}',[HomeController::class,'hasilanalisis'])->name('hasilanalisis');
Route::get('/psikologispernikahan',[HomeController::class,'infopsikologis'])->name('infopsikologis');
Route::get('/infopranikah',[HomeController::class,'infopranikah'])->name('infopranikah');

});

Route::get('/rumus-user-helper-demo', function () {
    return Rumus::CFCombine(2, 5);
});

Downloads/Tugas Akhir Nurma/app/Models/Pakar.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;


class Pakar extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    protected $fillable = [
        'email', 'password',
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $guard_name = 'web';

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    // Define the relationship with KesiapanPsikologis
    public function kesiapanPsikologis()
    {
        return $this->hasMany(KesiapanPsikologis::class, 'pakar_id');
    }
}

Downloads/Tugas Akhir Nurma/app/Http/Controllers/PakarController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Models\Pakar;
use App\Models\jawaban;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Http\Middleware\RedirectIfAuthenticated;

class PakarController extends Controller
{
//     public function __construct()
//     {
//         $this->middleware('auth:pakar');
//     }
    
//     public function index()
//     {
//         // Gunakan guard 'admin'
//         if (Auth::guard('pakar')->check()) {
//             // Pengguna admin telah terotentikasi
//         }
//     }
    
    public function indexpakar(){
        $pakar = Pakar::get();
       return view('pakar.indexpakar',compact('pakar'));
    } 

    public function createpakar(){
         return view('pakar.createpakar');
    }

    public function storepakar(Request $request){

         $validator = Validator::make($request->all(),[
              'email' => 'required|email',
              'password' => 'required',
         ]);

         if($validator->fails()) return redirect()->back()->withInput()->withErrors($validator);

         $pakar['email']      = $request->email;
         $pakar['password']   = Hash::make($request->password);

         Pakar::create($pakar);

         return redirect()->route('admin.indexpakar')->with('success','Data berhasil ditambahkan');
         }

    public function editpakar(Request $request,$id){
         $pakar = Pakar::find($id);

         return view('pakar.editpakar',compact('pakar'));
    }

    public function updatepakar(Request $request,$id){
         $validator = Validator::make($request->all(),[
              'email'    => 'required|email',
              'password' => 'nullable',
         ]);

         if($validator->fails()) return redirect()->back()->withInput()->withErrors($validator);

         $pakar['email']      = $request->email;
         if($request->password){
         $pakar['password']   = Hash::make($request->password);
         }

         Pakar::whereId($id)->update($pakar);

         return redirect()->route('admin.indexpakar')->with('success','Data berhasil diubah');
    }

    public function deletepakar(Request $request,$id){
         $pakar = Pakar::find($id);

         if($pakar)
              $pakar->delete();

         return redirect()->route('admin.indexpakar')->with('success','Data berhasil dihapus');
    }

    public function pakarlogin(){
     return view('pakarlogin');
 }

 public function pakarlogin_proses(Request $request)
{
    $request->validate([
        'email' => 'required|email',
        'password' => 'required'
    ]);

    // Ambil semua data pengguna dari tabel 'pakar'
    $pakars = Pakar::get();

    // Loop melalui setiap pengguna dan cek apakah ada yang cocok dengan email dan password yang diberikan
    foreach ($pakars as $pakar) {
        if ($pakar->email === $request->email && Hash::check($request->password, $pakar->password)) {
            return redirect()->route('admin.dashboard');
        }
    }

    // Jika tidak ada pengguna yang cocok, kembalikan ke halaman login dengan pesan kesalahan
    return redirect()->route('pakarlogin')->with('failed', 'Email atau Password Salah');
} 
}

Downloads/Tugas Akhir Nurma/resources/views/pakar/createpakar.blade.php
@extends('layout.main')

@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-4">
          <div class="col-sm-12 text-center">
            <h3 class="title">FORM TAMBAH PAKAR</h3>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <style>
    .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }
        .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */  
      }
      .card{
      background-color: #eff5ec;
      font-family: 'Times New Roman', Times, serif; 
    }
    
        </STYLE>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid">
            <form action="{{ route('admin.storepakar') }}" method="POST">
                @csrf
        <div class="row justify-content-center">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <!-- <h3 class="card-title">Form Tambah Data Pakar</h3> -->
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form>
                <div class="card-body">
                <div class="form-group">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email"> 
                    @if ($errors->has('email'))
                        <small class="form-text text-danger">{{ $errors->first('email') }}</small>
                    @endif
                </div>
                  <div class="form-group">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                    @if ($errors->has('password'))
                        <small class="form-text text-danger">{{ $errors->first('password') }}</small>
                    @endif
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
  <button type="submit" class="btn btn-primary float-right">SUBMIT</button>
</div>
                </div>
                </div>
                </div>
              </form>
        </form>
      </div><!-- /.container-fluid -->
    </section>
  </div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                                  
@endif
@endsection

Downloads/Tugas Akhir Nurma/resources/views/pakar/editpakar.blade.php
@extends('layout.main')

@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
      <div class="row mb-4">
          <div class="col-sm-12 text-center">
            <h3 class="title">FORM EDIT PAKAR</h3>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Edit User</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <style>
    .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }
        .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */  
      }
      .container-fluid {
        max-width: 800px; /* Set the maximum width of the container */
        margin: 0 auto; /* Center the container */
        padding: 20px; /* Add some padding */
      }
      .card{
      background-color: #eff5ec;
      font-family: 'Times New Roman', Times, serif; 
    }
    </STYLE>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid">
            <form action="{{ route('admin.updatepakar',['id' => $pakar->id]) }}" method="POST">
                @csrf
                @method('PUT')
        <div class="row">
          <!-- left column -->
          <div class="col-md-6 offset-md-3"> <!-- Add offset-md-3 to center the column -->
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <!-- <h3 class="card-title">Form Edit Data Pakar</h3> -->
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form>
                <div class="card-body">
                <div class="form-group">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ $pakar->email }}" placeholder="Enter email"> 
                    @if ($errors->has('email'))
                        <small class="form-text text-danger">{{ $errors->first('email') }}</small>
                    @endif
                </div>
                  <div class="form-group">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="Password">
                    @if ($errors->has('password'))
                        <small class="form-text text-danger">{{ $errors->first('password') }}</small>
                    @endif
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
  <button type="submit" class="btn btn-primary float-right">SUBMIT</button>
</div>
                </div>
                </div>
                </div>
              </form>
        </form>
      </div><!-- /.container-fluid -->
    </section>
  </div>

<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                                  
@endif
@endsection

Downloads/Tugas Akhir Nurma/resources/views/pakar/indexpakar.blade.php
@extends('layout.main')
@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />
@endsection
@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-12">
            <h3 class="title">DATA PAKAR</h3>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Data User</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <style>
  table {
    width: 100%; /* Sesuaikan lebar tabel sesuai kebutuhan */
    text-align: left;
    }
    .faktor-column {
      white-space: pre-line;
      word-wrap: break-word;
      max-width: 140px; 
    }
    .card{
      background-color: #eff5ec;
      font-family: 'Times New Roman', Times, serif; 
    margin-right: 30px; /* Adds left and right margins */
    margin-left:18px; 
    text-align: center;
    }
    .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */
    }
    .top-right-button {
      background-color: #343a40; /* Abu-abu tua */
            border-color: #343a40; /* Abu-abu tua */
            color: white;
            margin-top: 5px; /* Adjust this value as needed */
        }
        .btn-dark-gray {
            background-color: #343a40; /* Abu-abu tua */
            border-color: #343a40; /* Abu-abu tua */
            color: white;
            font-family: 'Times New Roman', Times, serif;
        }
        .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }
        /* padding-left: 100px;
        padding-right: 80px; */
        #serverside th,
#serverside td {
    text-align: center;
    vertical-align: middle; /* Ensures text is vertically centered as well */
    background-color: #eff5ec;
}

/* Optional: Add some styling to the table */
#serverside {
    width: 100%; /* Adjust this value to set the table width as needed */
    border-collapse: collapse; /* Ensures there is no space between table cells */
    text-align: center;
}

#serverside th,
#serverside td {
    padding: 10px; /* Adds some padding for better readability */
    border: 1px solid #ddd; /* Adds a border to the cells */
    text-align: center;
}

#serverside th {
    background-color: #eff5ec; /* Adds a background color to the header */
}
      
  </style>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <div class="row">
          <div class="col-12">
          <div class="container-fluid relative-container">
          <a href="{{ route('admin.createpakar') }}" class="btn btn-dark-gray top-right-button mb-3">TAMBAH PAKAR</a>
      </DIV>
            <div class="card">
              <div class="card-header">

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <!-- <input type="text" name="table_search" class="form-control float-right" placeholder="Search"> -->

                    <div class="input-group-append">
                     
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap" id="pakar">
                  <thead>
                    <tr>
                      <th>No.</th>
                      <th>Email</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($pakar as $p)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $p->email }}</td>
                            <td>
                                <a href="{{ route('admin.editpakar',['id' => $p->id]) }}" class="btn btn-primary"><i class="fas fa-pen"></i>Edit</a>
                                <a data-toggle="modal" data-target="#modal-hapus{{ $p->id }}" class="btn btn-danger"><i class="fas fa-trash-alt"></i>Hapus</a>
                            </td>
                        </tr>
                        <div class="modal fade" id="modal-hapus{{ $p->id }}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning">
        <h4 class="title">Konfirmasi Hapus Data</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="text-center">Apakah kamu yakin ingin menghapus data pakar <b>{{ $p->email }}</b>?</p>
      </div>
      <form action="{{ route('admin.deletepakar',['id' => $p->id]) }}" method="POST">
        @csrf
        @method('DELETE')
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Tidak</button>
          <button type="submit" class="btn btn-danger">Ya, Hapus</button>
        </div>
      </form>
    </div>
  </div>
</div>
                </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
                    @endforeach    
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>

  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                              
@endif
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
<script>
$(document).ready( function () {
    $('#pakar').DataTable();
} );
</script>
@endsection