Downloads/Tugas Akhir Nurma/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PakarController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\helper\Rumus;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     echo "Hello World"; 
// });

Route::get('/login',[LoginController::class,'index'])->name('login')->middleware('guest');
Route::get('/loginadmin',[PakarController::class,'pakarlogin'])->name('pakarlogin');
Route::post('/login-proses',[LoginController::class,'login_proses'])->name('login-proses');
Route::post('/loginadmin-proses',[PakarController::class,'pakarlogin_proses'])->name('pakarlogin-proses');
Route::get('/logout',[LoginController::class,'logout'])->name('logout');
Route::get('/register',[LoginController::class,'register'])->name('register');
Route::post('/register-proses',[LoginController::class,'register_proses'])->name('register-proses');

Route::group(['prefix' => 'admin', 'as' => 'admin.'] , function(){
Route::get('/dashboard',[HomeController::class,'dashboard'])->name('dashboard');

Route::get('/user',[HomeController::class,'index'])->name('index');

Route::get('/edituser/{id}',[HomeController::class,'edituser'])->name('edituser');
Route::put('/updateuser/{id}',[HomeController::class,'updateuser'])->name('updateuser');
Route::delete('/deleteuser/{id}',[HomeController::class,'deleteuser'])->name('deleteuser');

Route::get('/pakar',[PakarController::class,'indexpakar'])->name('indexpakar');
Route::get('/createpakar',[PakarController::class,'createpakar'])->name('createpakar');
Route::post('/storepakar',[PakarController::class,'storepakar'])->name('storepakar');

Route::get('/editpakar/{id}',[PakarController::class,'editpakar'])->name('editpakar');
Route::put('/updatepakar/{id}',[PakarController::class,'updatepakar'])->name('updatepakar');
Route::delete('/deletepakar/{id}',[PakarController::class,'deletepakar'])->name('deletepakar');

Route::get('/kesiapanpsikologis',[HomeController::class,'kesiapanpsikologis'])->name('kesiapanpsikologis');
Route::get('/createkesiapanpsikologis',[HomeController::class,'createkesiapanpsikologis'])->name('createkesiapanpsikologis');
Route::post('/storekesiapanpsikologis',[HomeController::class,'storekesiapanpsikologis'])->name('storekesiapanpsikologis');

Route::get('/editkesiapanpsikologis/{id}',[HomeController::class,'editkesiapanpsikologis'])->name('editkesiapanpsikologis');
Route::put('/updatekesiapanpsikologis/{id}',[HomeController::class,'updatekesiapanpsikologis'])->name('updatekesiapanpsikologis');
Route::delete('/deletekesiapanpsikologis/{id}',[HomeController::class,'deletekesiapanpsikologis'])->name('deletekesiapanpsikologis');


Route::get('/jawabanuser',[HomeController::class,'jawabanuser'])->name('jawabanuser');

Route::get('/print-data/{id}',[HomeController::class,'getDataPrint']);

});

Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
Route::get('/dashboarduser',[HomeController::class,'dashboarduser'])->name('dashboarduser');

Route::get('/analisis',[HomeController::class,'indexanalisis'])->name('indexanalisis');
Route::post('/storeanalisis',[HomeController::class,'storeanalisis'])->name('storeanalisis');
Route::delete('/deleteanalisis/{id}',[HomeController::class,'deleteanalisis'])->name('deleteanalisis');
Route::get('/analisispsikologis1',[HomeController::class,'analisispsikologis1'])->name('analisispsikologis1');
Route::post('/storepsikologis',[HomeController::class,'storepsikologis'])->name('storepsikologis');
Route::get('/analisispsikologis2',[HomeController::class,'analisispsikologis2'])->name('analisispsikologis2');
Route::get('/hasilanalisis/{id}',[HomeController::class,'hasilanalisis'])->name('hasilanalisis');
Route::get('/psikologispernikahan',[HomeController::class,'infopsikologis'])->name('infopsikologis');
Route::get('/infopranikah',[HomeController::class,'infopranikah'])->name('infopranikah');

});

Route::get('/rumus-user-helper-demo', function () {
    return Rumus::CFCombine(2, 5);
});

Downloads/Tugas Akhir Nurma/resources/views/kesiapan psikologis/create.blade.php
@extends('layout.main')

@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-sm-12 text-center">
            <h3 class="title">FORM TAMBAH PERTANYAAN</h3>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Tambah User</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <section class="content">
      <div class="container-fluid">
            <form action="{{ route('admin.storekesiapanpsikologis') }}" method="POST">
                @csrf
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <!-- <h3 class="card-title">Form Tambah Pertanyaan</h3> -->
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <style>
    .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }
        .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */  
      }
      .card{
      background-color: #eff5ec;
      font-family: 'Times New Roman', Times, serif; 
    }
    
        </STYLE>
              <form>
                <div class="card-body">
                <div class="form-group">
                <!-- <div class="col-4"> -->
                    <label for="faktor" class="form-label">Faktor</label>
                    <select class="form-control" id="faktor" name="faktor">
                    <option>Kesiapan Emosi</option>
                    <option>Kesiapan Sosial</option>
                    <option>Kesiapan Peran</option>
                    <option>Kesiapan Finansial</option>
                    <option>Kesiapan Spiritual</option>
                    <option>Kesiapan Reproduksi/Seksual</option>
                    <option>Kematangan Usia</option>
                    <option>Kemampuan Berkomunikasi</option>
                    </select>
                    @if ($errors->has('faktor'))
                        <small class="form-text text-danger">{{ $errors->first('faktor') }}</small>
                    @endif
                </div>
                <!-- </div> -->
                <div class="form-group">
                <!-- <div class="col-4"> -->
                <label for="gender" class="form-label">Gender</label>
                <select class="form-control" id="gender" name="gender">
                    <option>Laki-Laki</option>
                    <option>Perempuan</option>
                    <option>Umum</option>
                    </select>
                    @if ($errors->has('gender'))
               <small class="form-text text-danger">{{ $errors->first('gender') }}</small>
               @endif
                </div>
                <div class="form-group">
                    <label for="kesiapan" class="form-label">Pertanyaan Psikologis</label>
                    @if ($errors->has('kesiapan'))
                        <small class="form-text text-danger">{{ $errors->first('kesiapan') }}</small>
                    @endif
                    <input type="text" class="form-control" id="kesiapan" name="kesiapan" placeholder="Masukkan pertanyaan psikologis"> 
                </div>
                <div class="form-group">
                <label for="nilai_bobot" class="form-label">
    Bobot Jawaban
    <span class="text-muted">(Gunakan titik untuk angka desimal, contoh : 0.90)</span>
</label>
   
                <div class="row">
                  <div class="col-2">
                  @if ($errors->has('tidak'))
                        <small class="form-text text-danger">{{ $errors->first('tidak') }}</small>
                    @endif
                    Tidak
                    <input type="text" class="form-control" id="tidak" name="tidak"  placeholder="Enter nilai" step="any">
                  </div>
                  <div class="col-2">
                  @if ($errors->has('tidak_tahu'))
                        <small class="form-text text-danger">{{ $errors->first('tidak_tahu') }}</small>
                    @endif
                    Tidak Tahu
                    <input type="text" class="form-control" id="tidak_tahu" name="tidak_tahu" placeholder="Enter nilai" step="any">
                  </div>
                  <div class="col-2">
                  @if ($errors->has('sedikit_setuju'))
                        <small class="form-text text-danger">{{ $errors->first('sedikit_setuju') }}</small>
                    @endif
                    Sedikit Setuju
                    <input type="text" class="form-control" id="sedikit_setuju" name="sedikit_setuju" placeholder="Enter nilai" step="any">
                  </div>
                  <div class="col-2">
                  @if ($errors->has('cukup_setuju'))
                        <small class="form-text text-danger">{{ $errors->first('cukup_setuju') }}</small>
                    @endif
                    Cukup Setuju
                    <input type="text" class="form-control" id="cukup_setuju" name="cukup_setuju" placeholder="Enter nilai" step="any">
                  </div>
                  <div class="col-2">
                  @if ($errors->has('setuju'))
                        <small class="form-text text-danger">{{ $errors->first('setuju') }}</small>
                    @endif
                    Setuju
                    <input type="text" class="form-control" id="setuju" name="setuju" placeholder="Enter nilai" step="any">
                  </div>
                  <div class="col-2">
                  @if ($errors->has('sangat_setuju'))
                        <small class="form-text text-danger">{{ $errors->first('sangat_setuju') }}</small>
                    @endif
                    Sangat Setuju
                    <input type="text" class="form-control" id="sangat_setuju" name="sangat_setuju" placeholder="Enter nilai" step="any">
                  </div>  
                </div>
                </div>
                <div class="form-group">
                <label for="nilai_bobot" class="form-label">
    Nilai CFH
    <span class="text-muted">(Gunakan titik untuk angka desimal, contoh : 0.60)</span>
</label>
                    @if ($errors->has('CFH'))
                        <small class="form-text text-danger">{{ $errors->first('CFH') }}</small>
                    @endif
                    <div class="row">
                    <div class="col-2">
                    <input type="text" class="form-control" id="CFH" name="CFH" placeholder="Enter nilai" step="any"> 
                </div>
                </div>
                </div>
                
              <!-- /.card-body -->
                </div>
                

                </div>
                <!-- /.card-body -->

               
                <div class="card-footer">
  <button type="submit" class="btn btn-primary float-right">SUBMIT</button>
</div>
                </div>
                </div>
                </div>
              </form>
        </form>
      </div><!-- /.container-fluid -->
    </section>
  </div>

<!-- jQuery -->
<script src="{{ asset('lte/plugins/jquery/jquery.min.js') }}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset('lte/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('lte/dist/js/adminlte.min.js') }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                                  
@endif
@endsection

Downloads/Tugas Akhir Nurma/resources/views/kesiapan psikologis/index.blade.php
@extends('layout.main')
@section('css')
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />
@endsection
@section('content')
<div class="content-wrapper">
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('lte/dist/css/adminlte.min.css') }}">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
        <div class="col-12">
            <h3 class="title">PERTANYAAN PSIKOLOGIS</h3>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <!-- <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Data User</li> -->
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <style>
  
    
    .content-wrapper {
        background-color: #dfe6da; /* Warna pink soft */ /* Ubah kode warna sesuai preferensi Anda */
    }
    .top-right-button {
      background-color: #343a40; /* Abu-abu tua */
            border-color: #343a40; /* Abu-abu tua */
            color: white;
            margin-top: 5px; /* Adjust this value as needed */
        }
        .btn-dark-gray {
            background-color: #343a40; /* Abu-abu tua */
            border-color: #343a40; /* Abu-abu tua */
            color: white;
            font-family: 'Times New Roman', Times, serif;
        }
        .title {
            font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
            color: black; /* Warna teks menjadi hitam */
            margin-bottom: 0px; /* Jarak bawah antara judul */
            margin-top: 0px; /* Mengurangi margin atas untuk mendekatkan dengan logo */
            text-align: center; /* Menempatkan teks di tengah */
            font-weight: bold; /* Membuat teks tebal */
        }

        </style>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
      <div class="row">
          <div class="col-12">
          <div class="container-fluid relative-container">
            <a href="{{ route('admin.createkesiapanpsikologis') }}" class="btn btn-dark-gray top-right-button mb-3">TAMBAH PERTANYAAN</a>
            </DIV>
            <div class="card">
              <div class="card-header">

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <!-- <input type="text" name="table_search" class="form-control float-right" placeholder="Search"> -->

                    <div class="input-group-append">
                      
                    </div>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <style>
    table {
    width: 100%; /* Sesuaikan lebar tabel sesuai kebutuhan */
    text-align: left;
    }
    .question-column {
      white-space: pre-line;
      word-wrap: break-word;
      max-width: 130px; 
      text-align: left;
    }
    .faktor-column {
      white-space: pre-line;
      word-wrap: break-word;
      max-width: 100px; 
      text-align: left;
    }
   
    .card{
      background-color: #eff5ec;
      font-family: 'Times New Roman', Times, serif; 
    margin-right: 30px; /* Adds left and right margins */
    margin-left:15px; 
    text-align: center;
    }
    #serverside th,
#serverside td {
    text-align: center;
    vertical-align: middle; /* Ensures text is vertically centered as well */
    background-color: #eff5ec;
}

/* Optional: Add some styling to the table */
#serverside {
    width: 100%; /* Adjust this value to set the table width as needed */
    border-collapse: collapse; /* Ensures there is no space between table cells */
    text-align: center;
}

#serverside th,
#serverside td {
    padding: 10px; /* Adds some padding for better readability */
    border: 1px solid #ddd; /* Adds a border to the cells */
    text-align: center;
}

#serverside th {
    background-color: #eff5ec; /* Adds a background color to the header */
}

    </style>
  <!-- <title>Your Page Title</title> -->
</head>
              <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap" id="pertanyaan">
                  <thead>
                    <tr>
                      <th>No.</th>
                      <th>Faktor</th>
                      <th>Kode</th>
                      <th>Pertanyaan</th>
                      <th>Bobot Jawaban</th>
                      <th>CFH</th>
                      <th>Gender</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach ($pertanyaan as $p)
                        <tr>
                            <td class="faktor-column"> {{ $loop->iteration }}</td>
                            <td class="faktor-column">{{ $p->faktor }}</td>
                            <td class="faktor-column">{{ $p->kode_kesiapan }}</td>
                            <td class="question-column">{{ $p->kesiapan }}</td>
                            <td>
                            <table class="table table-hover">
                              <tbody>
                                  <tr data-widget="expandable-table" aria-expanded="false">
                                      <td>
                                          <button type="button" class="btn btn-primary p-0">
                                              <i class="expandable-table-caret fas fa-caret-right fa-fw"></i>
                                          </button>
                                          Nilai
                                      </td>
                                  </tr>
                                  <tr class="expandable-body">
                                      <td>
                                          <div class="p-0">
                                              <table>
                                                  <tbody class="faktor-column">
                                                      <tr>
                                                          <td>Tidak={{ $p->tidak }}</td>
                                                      </tr>
                                                      <tr>
                                                          <td>Tidak Tahu={{ $p->tidak_tahu }}</td>
                                                      </tr>
                                                      <tr>
                                                          <td>Sedikit Setuju={{ $p->sedikit_setuju }}</td>
                                                      </tr>
                                                      <tr>
                                                          <td>Cukup Setuju={{ $p->cukup_setuju }}</td>
                                                      </tr>
                                                      <tr>
                                                          <td>Setuju={{ $p->setuju }}</td>
                                                      </tr>
                                                      <tr>
                                                          <td>Sangat Setuju={{ $p->sangat_setuju }}</td>
                                                      </tr>
                                                  </tbody>
                                              </table>
                                          </div>
                                      </td>
                                  </tr>
                              </tbody>
                          </table>
                            </td>
                            <td class="faktor-column">{{ $p->CFH }}</td>
                            <td class="faktor-column">{{ $p->gender }}</td>
                            <td>
                                <a href="{{ route('admin.editkesiapanpsikologis',['id' => $p->id]) }}" class="btn btn-primary"><i class="fas fa-pen"></i>Edit</a>
                            </td>
                        </tr>
                        <div class="modal fade" id="modal-hapus{{ $p->id }}">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Konfirmasi Hapus Data</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Apakah kamu yakin ingin menghapus data user <b>{{ $p->kode_kesiapan }}</b></p>
            </div>
                <form action="{{ route('admin.deletekesiapanpsikologis',['id' => $p->id]) }}" method="POST">
                    @csrf
                    @method('DELETE')
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
                    <button type="submit" class="btn btn-primary">Ya, Hapus</button>
                </div>
                </form>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
      </div>
      <!-- /.modal -->
                    @endforeach    
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if($message = Session::get('success'))
<script> 
Swal.fire({
  position: "center-center",
  icon: "success",
  title: "{{ $message }}",
  showConfirmButton: false,
  timer: 2500
});
</script>                                  
@endif 
@endsection

@section('scripts')
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
<script>
$(document).ready( function () {
    $('#pertanyaan').DataTable();
} );
</script>
@endsection