Downloads/Tugas Akhir Nurma/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PakarController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\Controller;
use App\Http\Middleware\RedirectIfAuthenticated;
use App\helper\Rumus;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     echo "Hello World"; 
// });

Route::get('/login',[LoginController::class,'index'])->name('login')->middleware('guest');
Route::get('/loginadmin',[PakarController::class,'pakarlogin'])->name('pakarlogin');
Route::post('/login-proses',[LoginController::class,'login_proses'])->name('login-proses');
Route::post('/loginadmin-proses',[PakarController::class,'pakarlogin_proses'])->name('pakarlogin-proses');
Route::get('/logout',[LoginController::class,'logout'])->name('logout');
Route::get('/register',[LoginController::class,'register'])->name('register');
Route::post('/register-proses',[LoginController::class,'register_proses'])->name('register-proses');

Route::group(['prefix' => 'admin', 'as' => 'admin.'] , function(){
Route::get('/dashboard',[HomeController::class,'dashboard'])->name('dashboard');

Route::get('/user',[HomeController::class,'index'])->name('index');

Route::get('/edituser/{id}',[HomeController::class,'edituser'])->name('edituser');
Route::put('/updateuser/{id}',[HomeController::class,'updateuser'])->name('updateuser');
Route::delete('/deleteuser/{id}',[HomeController::class,'deleteuser'])->name('deleteuser');

Route::get('/pakar',[PakarController::class,'indexpakar'])->name('indexpakar');
Route::get('/createpakar',[PakarController::class,'createpakar'])->name('createpakar');
Route::post('/storepakar',[PakarController::class,'storepakar'])->name('storepakar');

Route::get('/editpakar/{id}',[PakarController::class,'editpakar'])->name('editpakar');
Route::put('/updatepakar/{id}',[PakarController::class,'updatepakar'])->name('updatepakar');
Route::delete('/deletepakar/{id}',[PakarController::class,'deletepakar'])->name('deletepakar');

Route::get('/kesiapanpsikologis',[HomeController::class,'kesiapanpsikologis'])->name('kesiapanpsikologis');
Route::get('/createkesiapanpsikologis',[HomeController::class,'createkesiapanpsikologis'])->name('createkesiapanpsikologis');
Route::post('/storekesiapanpsikologis',[HomeController::class,'storekesiapanpsikologis'])->name('storekesiapanpsikologis');

Route::get('/editkesiapanpsikologis/{id}',[HomeController::class,'editkesiapanpsikologis'])->name('editkesiapanpsikologis');
Route::put('/updatekesiapanpsikologis/{id}',[HomeController::class,'updatekesiapanpsikologis'])->name('updatekesiapanpsikologis');
Route::delete('/deletekesiapanpsikologis/{id}',[HomeController::class,'deletekesiapanpsikologis'])->name('deletekesiapanpsikologis');


Route::get('/jawabanuser',[HomeController::class,'jawabanuser'])->name('jawabanuser');

Route::get('/print-data/{id}',[HomeController::class,'getDataPrint']);

});

Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
Route::get('/dashboarduser',[HomeController::class,'dashboarduser'])->name('dashboarduser');

Route::get('/analisis',[HomeController::class,'indexanalisis'])->name('indexanalisis');
Route::post('/storeanalisis',[HomeController::class,'storeanalisis'])->name('storeanalisis');
Route::delete('/deleteanalisis/{id}',[HomeController::class,'deleteanalisis'])->name('deleteanalisis');
Route::get('/analisispsikologis1',[HomeController::class,'analisispsikologis1'])->name('analisispsikologis1');
Route::post('/storepsikologis',[HomeController::class,'storepsikologis'])->name('storepsikologis');
Route::get('/analisispsikologis2',[HomeController::class,'analisispsikologis2'])->name('analisispsikologis2');
Route::get('/hasilanalisis/{id}',[HomeController::class,'hasilanalisis'])->name('hasilanalisis');
Route::get('/psikologispernikahan',[HomeController::class,'infopsikologis'])->name('infopsikologis');
Route::get('/infopranikah',[HomeController::class,'infopranikah'])->name('infopranikah');

});

Route::get('/rumus-user-helper-demo', function () {
    return Rumus::CFCombine(2, 5);
});

Downloads/Tugas Akhir Nurma/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

        use HasRoles;
    
        protected $fillable = [
            'email', 'password','nama_lengkap','jenis_kelamin'
        ];
    
        protected $hidden = [
            'password', 'remember_token',
        ];
    
        protected $guard_name = 'web';

    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ]; 

    public function jawabanusers()
    {
        return $this->hasMany(JawabanUser::class, 'user_id');
    }

    public function jawabans()
    {
        return $this->hasMany(Jawaban::class, 'user_id');
    }
}

Downloads/Tugas Akhir Nurma/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\User;

class UserController extends Controller
{
    // public function __construct()
    // {
    //     $this->middleware('auth:pengantin');
    // }
    
    // public function index()
    // {
    //     // Gunakan guard 'user'
    //     if (Auth::guard('pengantin')->check()) {
    //         // Pengguna user telah terotentikasi
    //     }
    // }
}

Downloads/Tugas Akhir Nurma/resources/views/user/analisispsikologis1.blade.php
@extends('USER.main')

@section('content')


<!DOCTYPE html>





<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0">Form Analisis</h1> -->
                </div><!-- /.col -->
                
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- <div class="card"> -->
                        <!-- <div class="card-header"> -->
                            <!-- <h3 class="card-title">Pilih Jawaban</h3> -->
                        <!-- </div> -->
    <style>
    .table {
    width: 100%; /* Sesuaikan lebar tabel sesuai kebutuhan */
    text-align: center;
    }
    .card-body {
    padding: 20px; /* Tambahkan padding di dalam card body */
    margin-bottom: 20px; /* Tambahkan margin di bawah card body */
}
.card-body {
    background-color:  #eff5ec; /* Ubah warna latar belakang card body */
    padding: 10px; /* Tambahkan padding di dalam card body */
    border-radius: 10px; /* Agar card body memiliki sudut yang lebih melengkung */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Tambahkan bayangan pada card body */
    max-width: 800px; /* Atur lebar maksimum card body */
    margin: auto; /* Atur margin auto untuk posisi tengah */
margin-top: 80px;
font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
color: black; /* Warna teks menjadi hitam */
}

.card-body {
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Tambahkan bayangan pada card body */
    border-radius: 10px; /* Agar card body memiliki sudut yang lebih melengkung */
    font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
    color: black; /* Warna teks menjadi hitam */
}

    .question-column {
      white-space: pre-line;
      word-wrap: break-word;
      max-width: 180px; 
      text-align: left;
      font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
      color: black; /* Warna teks menjadi hitam */
    }
    .pilihan-column {
      text-align: left;
      max-width: 30px; 
      font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
      color: black; /* Warna teks menjadi hitam */
    }

    .content-wrapper {
        background-color: #dfe6da; 
    }

    .controls {
    display: flex;
    justify-content: left;  /* Menempatkan isi flexbox di pojok kanan */
    margin-top: 10px; /* Jarak antara tombol dengan card-body */
    padding-right: 100px;
    padding-LEFT: 100px;
}

.controls button {
    margin-right: 10px; /* Memberi ruang di sebelah kanan tombol */
    background-color: black; /* Ubah warna latar belakang tombol */
    color: white; /* Ubah warna teks tombol */
    border: none; 
    font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
    
}

.nomor{
    display: flex;
    justify-content: flex-end; 
    margin-bottom: 5px; 
    font-weight: bold;
}
.soal{
    margin-top: 5px; 
    font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
    color: black; /* Warna teks menjadi hitam */
}

    </style>
                      <div class="card-body">
    @php
        // Filter pertanyaan yang sesuai dengan gender "Laki-Laki" atau "Umum"
        $filteredPertanyaan = $pertanyaan->filter(function ($p) {
            return $p->gender == 'Laki-Laki' || $p->gender == 'Umum';
        });
        $totalPertanyaan = $filteredPertanyaan->count();
        $index = 0;
    @endphp

    <form id="quizForm" action="{{ route('user.storepsikologis') }}" method="POST">
        @csrf
        <div class="slider">
            @foreach ($filteredPertanyaan as $p)
                <div class="slide">
                    <p class="nomor">{{ ++$index }} / {{ $totalPertanyaan }}</p>
                    <h5 class="soal">{{ $p->kesiapan }}</h5>
                    <div class="pilihan">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_1" value="{{ $p->tidak }}|{{ $p->CFH }}|tidak" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_1">
                                Tidak
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->tidak_tahu }}|{{ $p->CFH }}|tidaktahu" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Tidak Tahu
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->sedikit_setuju }}|{{ $p->CFH }}|sedikitsetuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Sedikit Setuju
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->cukup_setuju }}|{{ $p->CFH }}|cukupsetuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Cukup Setuju
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->setuju }}|{{ $p->CFH }}|setuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Setuju
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->sangat_setuju }}|{{ $p->CFH }}|sangatsetuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Sangat Setuju
                            </label>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <!-- <div class="controls"> -->
        </div>
    </form>
</div>
</div>

<div class="controls">
    <button class="btn btn-primary" id="prevBtn" onclick="prevSlide()">PREV</button>
    <button class="btn btn-primary" id="nextBtn" onclick="nextSlide()">NEXT</button>
    <button type="button" class="btn btn-primary" id="submitBtn" onclick="submitForm()">SUBMIT</button>
</div>
</form>
</div>

<script>
    var currentSlide = 0;
    showSlide(currentSlide);

    function showSlide(n) {
        var slides = document.getElementsByClassName("slide");
        for (var i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slides[n].style.display = "block";
        if (n === 0) {
            document.getElementById("prevBtn").style.display = "none";
        } else {
            document.getElementById("prevBtn").style.display = "inline";
        }
        if (n === slides.length - 1) {
            document.getElementById("nextBtn").style.display = "none";
            document.getElementById("submitBtn").style.display = "inline";
        } else {
            document.getElementById("nextBtn").style.display = "inline";
            document.getElementById("submitBtn").style.display = "none";
        }
    }

    function prevSlide() {
        currentSlide--;
        showSlide(currentSlide);
    }

    function nextSlide() {
        if (validateSlide(currentSlide)) {
            currentSlide++;
            showSlide(currentSlide);
        } else {
            alert("Silakan pilih jawaban sebelum melanjutkan.");
        }
    }

    function validateSlide(n) {
        var slide = document.getElementsByClassName("slide")[n];
        var inputs = slide.querySelectorAll("input[type='radio'], input[type='checkbox']");

        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].checked) {
                return true;
            }
        }
        return false;
    }

    function submitForm() {
        if (validateSlide(currentSlide)) {
            var form = document.getElementById("quizForm");
            form.action = "{{ route('user.storepsikologis') }}";
            form.submit();
        } else {
            alert("Silakan pilih jawaban sebelum mengirimkan formulir.");
        }
    }
</script>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

Downloads/Tugas Akhir Nurma/resources/views/user/analisispsikologis2.blade.php
@extends('USER.main')

@section('content')


<!DOCTYPE html>





<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <!-- <h1 class="m-0">Form Analisis</h1> -->
                </div><!-- /.col -->
                
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <!-- <div class="card"> -->
                        <!-- <div class="card-header"> -->
                            <!-- <h3 class="card-title">Pilih Jawaban</h3> -->
                        <!-- </div> -->
    <style>
    .table {
    width: 100%; /* Sesuaikan lebar tabel sesuai kebutuhan */
    text-align: center;
    }
    .card-body {
    padding: 20px; /* Tambahkan padding di dalam card body */
    margin-bottom: 20px; /* Tambahkan margin di bawah card body */
}
.card-body {
    background-color:  #eff5ec; /* Ubah warna latar belakang card body */
    padding: 10px; /* Tambahkan padding di dalam card body */
    border-radius: 10px; /* Agar card body memiliki sudut yang lebih melengkung */
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Tambahkan bayangan pada card body */
    max-width: 800px; /* Atur lebar maksimum card body */
    margin: auto; /* Atur margin auto untuk posisi tengah */
margin-top: 80px;
font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
color: black; /* Warna teks menjadi hitam */
}

.card-body {
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Tambahkan bayangan pada card body */
    border-radius: 10px; /* Agar card body memiliki sudut yang lebih melengkung */
    font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
    color: black; /* Warna teks menjadi hitam */
}

    .question-column {
      white-space: pre-line;
      word-wrap: break-word;
      max-width: 180px; 
      text-align: left;
      font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
      color: black; /* Warna teks menjadi hitam */
    }
    .pilihan-column {
      text-align: left;
      max-width: 30px; 
      font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
      color: black; /* Warna teks menjadi hitam */
    }

    .content-wrapper {
        background-color: #dfe6da; 
    }

    .controls {
    display: flex;
    justify-content: left;  /* Menempatkan isi flexbox di pojok kanan */
    margin-top: 10px; /* Jarak antara tombol dengan card-body */
    padding-right: 100px;
    padding-LEFT: 100px;
}

.controls button {
    margin-right: 10px; /* Memberi ruang di sebelah kanan tombol */
    background-color: black; /* Ubah warna latar belakang tombol */
    color: white; /* Ubah warna teks tombol */
    border: none; 
    font-family: 'Times New Roman', Times, serif; /* Mengubah font agar lebih formal untuk judul cetak */
}

.nomor{
    display: flex;
    justify-content: flex-end; 
    margin-bottom: 5px; 
    font-weight: bold;
}
.soal{
    margin-top: 5px; 
}

    </style>
                      <div class="card-body">
    @php
        // Filter pertanyaan yang sesuai dengan gender "Perempuan" atau "Umum"
        $filteredPertanyaan = $pertanyaan->filter(function ($p) {
            return $p->gender == 'Perempuan' || $p->gender == 'Umum';
        });
        $totalPertanyaan = $filteredPertanyaan->count();
        $index = 0;
    @endphp

    <form id="quizForm" action="{{ route('user.storepsikologis') }}" method="POST">
        @csrf
        <div class="slider">
            @foreach ($filteredPertanyaan as $p)
                <div class="slide">
                    <p class="nomor">{{ ++$index }} / {{ $totalPertanyaan }}</p>
                    <h5 class="soal">{{ $p->kesiapan }}</h5>
                    <div class="pilihan">
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_1" value="{{ $p->tidak }}|{{ $p->CFH }}|tidak" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_1">
                                Tidak
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->tidak_tahu }}|{{ $p->CFH }}|tidaktahu" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Tidak Tahu
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->sedikit_setuju }}|{{ $p->CFH }}|sedikitsetuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Sedikit Setuju
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->cukup_setuju }}|{{ $p->CFH }}|cukupsetuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Cukup Setuju
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->setuju }}|{{ $p->CFH }}|setuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Setuju
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="{{ $p->id }}" id="jawaban_{{ $loop->iteration }}_2" value="{{ $p->sangat_setuju }}|{{ $p->CFH }}|sangatsetuju" step="any">
                            <label class="form-check-label" for="jawaban_{{ $loop->iteration }}_2">
                                Sangat Setuju
                            </label>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <!-- <div class="controls"> -->
        </div>
    </form>
</div>
</div>

<div class="controls">
    <button class="btn btn-primary" id="prevBtn" onclick="prevSlide()">PREV</button>
    <button class="btn btn-primary" id="nextBtn" onclick="nextSlide()">NEXT</button>
    <button type="button" class="btn btn-primary" id="submitBtn" onclick="submitForm()">SUBMIT</button>
</div>
</form>
</div>

<script>
    var currentSlide = 0;
    showSlide(currentSlide);

    function showSlide(n) {
        var slides = document.getElementsByClassName("slide");
        for (var i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slides[n].style.display = "block";
        if (n === 0) {
            document.getElementById("prevBtn").style.display = "none";
        } else {
            document.getElementById("prevBtn").style.display = "inline";
        }
        if (n === slides.length - 1) {
            document.getElementById("nextBtn").style.display = "none";
            document.getElementById("submitBtn").style.display = "inline";
        } else {
            document.getElementById("nextBtn").style.display = "inline";
            document.getElementById("submitBtn").style.display = "none";
        }
    }

    function prevSlide() {
        currentSlide--;
        showSlide(currentSlide);
    }

    function nextSlide() {
        if (validateSlide(currentSlide)) {
            currentSlide++;
            showSlide(currentSlide);
        } else {
            alert("Silakan pilih jawaban sebelum melanjutkan.");
        }
    }

    function validateSlide(n) {
        var slide = document.getElementsByClassName("slide")[n];
        var inputs = slide.querySelectorAll("input[type='radio'], input[type='checkbox']");

        for (var i = 0; i < inputs.length; i++) {
            if (inputs[i].checked) {
                return true;
            }
        }
        return false;
    }

    function submitForm() {
        if (validateSlide(currentSlide)) {
            var form = document.getElementById("quizForm");
            form.action = "{{ route('user.storepsikologis') }}";
            form.submit();
        } else {
            alert("Silakan pilih jawaban sebelum mengirimkan formulir.");
        }
    }
</script>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection